# Each route describes how an incoming URL is going to be processed by Platform.sh.
'https://www.{default}/':
  type: upstream
  upstream: 'Chul_SNS:http'

'https://{default}/':
  type: redirect
  to: 'https://www.{default}/'

'https://www.{default}/ws':
  type: upstream
  upstream: 'Chul_SNS:http'
  cache:
    enabled: false
